/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.stardata.observ.api;

import java.util.List;
import java.util.Optional;

import javax.annotation.Generated;
import javax.validation.Valid;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.context.request.NativeWebRequest;

import com.stardata.observ.vo.SpanListResponse;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Trace查询", description = "the Trace查询 API")
public interface SpansApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /spans : 获取Span列表
     *
     * @param spanSnapshotIds (optional)
     * @param conditions      在span快照ID基础上，增加的查询条件，支持SpanAttributes的各类属性作为条件。 (optional)
     * @param fromTime        单位ms (optional)
     * @param toTime          单位ms (optional)
     * @param minDuration     单位ms (optional)
     * @param maxDuration     单位ms (optional)
     * @param pageNo          访问页码 (optional)
     * @param pageSize        页面数据量，默认值20 (optional)
     * @return 成功 (status code 200)
     */
    @Operation(
            operationId = "getSpans",
            summary = "获取Span列表",
            description = "",
            tags = {"Trace查询"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "成功", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SpanListResponse.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/spans",
            produces = {"application/json"}
    )

    default ResponseEntity<SpanListResponse> getSpans(
            @Parameter(name = "spanSnapshotIds", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "spanSnapshotIds", required = false) List<String> spanSnapshotIds,
            @Parameter(name = "conditions", description = "在span快照ID基础上，增加的查询条件，支持SpanAttributes的各类属性作为条件。", in = ParameterIn.QUERY) @Valid @RequestParam(value = "conditions", required = false) String conditions,
            @Parameter(name = "fromTime", description = "单位ms", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fromTime", required = false) Long fromTime,
            @Parameter(name = "toTime", description = "单位ms", in = ParameterIn.QUERY) @Valid @RequestParam(value = "toTime", required = false) Long toTime,
            @Parameter(name = "minDuration", description = "单位ms", in = ParameterIn.QUERY) @Valid @RequestParam(value = "minDuration", required = false) Long minDuration,
            @Parameter(name = "maxDuration", description = "单位ms", in = ParameterIn.QUERY) @Valid @RequestParam(value = "maxDuration", required = false) Long maxDuration,
            @Parameter(name = "pageNo", description = "访问页码", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageNo", required = false) Integer pageNo,
            @Parameter(name = "pageSize", description = "页面数据量，默认值20", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : 0, \"data\" : { \"spans\" : [ { \"traceId\" : \"traceId\", \"cluster\" : \"cluster\", \"instance\" : \"instance\", \"software\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"serviceName\" : \"serviceName\", \"parentSpanId\" : \"parentSpanId\", \"platform\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"spanName\" : \"spanName\", \"spanId\" : \"spanId\", \"duration\" : 7, \"logCount\" : 9, \"application\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"timestamp\" : 2 }, { \"traceId\" : \"traceId\", \"cluster\" : \"cluster\", \"instance\" : \"instance\", \"software\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"serviceName\" : \"serviceName\", \"parentSpanId\" : \"parentSpanId\", \"platform\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"spanName\" : \"spanName\", \"spanId\" : \"spanId\", \"duration\" : 7, \"logCount\" : 9, \"application\" : { \"displayName\" : \"displayName\", \"name\" : \"name\" }, \"timestamp\" : 2 } ], \"pageCount\" : 5, \"pageNo\" : 6, \"pageSize\" : 1, \"totalCount\" : 5 }, \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
