spring.datasource.dynamic.datasource:
  data.url: jdbc:clickhouse://host.docker.internal:28123/otel?use_time_zone=GMT+8&use_server_time_zone=GMT+8
  config.url: jdbc:postgresql://host.docker.internal:25432/postgres?serverTimezone=GMT%2B8&useSSL=false&stringtype=unspecified
